import { Router } from 'express';
import * as c from '../controllers/reports.controller.js';
const r = Router();
r.get('/tenants', c.tenants);
r.get('/contracts', c.contracts);
r.get('/rental-income', c.rentalIncome);
r.get('/rooms', c.rooms);
r.get('/available-rooms', c.availableRooms);
r.get('/occupancy', c.occupancy);
r.get('/maintenance', c.maintenance);
r.get('/maintenance-voucher', c.maintenanceVoucher);
r.get('/maintenance-cost', c.maintenanceCost);
r.get('/monthly-bills', c.monthlyBills);
r.get('/billing-statement', c.billingStatement);
r.get('/charges-by-type', c.chargesByType);
r.get('/payments', c.payments);
r.get('/unpaid-balances', c.unpaidBalances);
r.get('/payments-by-method', c.paymentsByMethod);
r.get('/expenses', c.expenses);
r.get('/expense-voucher', c.expenseVoucher);
r.get('/expenses-by-category', c.expensesByCategory);
export default r;
